List manufacturerCompaniesList = [
  "Audi",
  "BMW",
  "Chevrolet",
  "DC Design",
  "Datsun",
  "Fiat",
  "Ford",
  "Force",
  "Honda",
  "Hyundai",
  "Jaguar",
  "Jeep",
  "KIA Motors",
  "Lamborghini",
  "Mahindra",
  "Maruti Suzuki",
  "Mercedes Benz",
  "MG Motor",
  "Nissan",
  "Renault",
  "Skoda",
  "Tata Motors",
  "Toyota",
  "Volkswagen",
  "Volvo"
];
// Manufacturer → Models mapping
Map<String, List<String>> vehicleModelsName = {
  "Audi": [
    "A1",
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "Q2",
    "Q3",
    "Q4 e-tron",
    "Q5",
    "Q6 e-tron",
    "Q7",
    "Q8",
    "e-tron",
    "e-tron GT",
    "A6 e-tron",
    "R8",
    "Q3 Sportback",
    "A8 L",
    "Q7 Technology",
    "Q8 e-tron",
    "RS Q8",
    "RS e-tron GT",
    "Q5 Sportback"
  ],
  "BMW": [
    "1 Series",
    "2 Series",
    "3 Series",
    "4 Series",
    "5 Series",
    "7 Series",
    "X1",
    "X2",
    "X3",
    "X4",
    "X5",
    "X6",
    "X7",
    "i3",
    "i4",
    "iX",
    "iX3",
    "Z4",
    "M3",
    "M5",
    "X1 sDrive18i",
    "iX1",
    "i7",
    "i5",
    "XM",
    "M2",
    "M4",
    "X5 M",
    "X6 M",
    "2 Series Gran Coupé"
  ],
  "Chevrolet": [
    "Spark",
    "Beat",
    "Cruze",
    "Captiva",
    "Malibu",
    "Sail",
    "Trailblazer",
    "Equinox",
    "Traverse",
    "Tahoe",
    "Camaro",
    "Corvette"
  ],
  "DC Design": ["DC Avanti", "DC2"],
  "Datsun": ["Go", "Go+", "Redi-Go", "Cross"],
  "Fiat": ["Punto", "Linea", "500", "500X", "Panda", "Tipo", "Bravo"],
  "Ford": [
    "Figo",
    "Aspire",
    "EcoSport",
    "Endeavour",
    "Mustang",
    "F-150",
    "Focus",
    "Fusion",
    "Ranger",
    "Territory",
    "Mustang Mach-E",
    "Bronco",
    "Escape"
  ],
  "Force Motors": ["Traveller", "Trax", "Gurkha", "One", "Motus"],
  "Honda": [
    "Amaze",
    "City",
    "Jazz",
    "WR-V",
    "BR-V",
    "HR-V",
    "CR-V",
    "Civic",
    "Accord",
    "Elevate",
    "City e:HEV",
    "Civic Type R",
    "HR-V Hybrid"
  ],
  "Hyundai": [
    "Santro",
    "Grand i10",
    "i20",
    "Verna",
    "Creta",
    "Tucson",
    "Venue",
    "Elantra",
    "Kona Electric",
    "Aura",
    "Sonata",
    "Alcazar",
    "Grand i10 Nios",
    "Exter",
    "Ioniq 5",
    "Santa Fe",
    "Palisade",
    "Kona"
  ],
  "Jaguar": [
    "XE",
    "XF",
    "XJ",
    "F-Type",
    "E-Pace",
    "F-Pace",
    "I-Pace",
    "XF Sportbrake"
  ],
  "Jeep": [
    "Compass",
    "Meridian",
    "Wrangler",
    "Grand Cherokee",
    "Cherokee",
    "Renegade",
    "Gladiator",
    "Wagoneer",
    "Grand Wagoneer"
  ],
  "KIA Motors": [
    "Sonet",
    "Seltos",
    "Carnival",
    "EV6",
    "Telluride",
    "Sportage",
    "Stinger",
    "Carens",
    "Sorento"
  ],
  "Lamborghini": ["Aventador", "Huracán", "Urus", "Sian", "Huracán STO"],
  "Mahindra": [
    "Thar",
    "Scorpio",
    "XUV700",
    "XUV300",
    "Bolero",
    "Marazzo",
    "Alturas G4",
    "KUV100",
    "BE 6",
    "XUV3XO",
    "Bolero Neo",
    "Scorpio Classic",
    "XUV400 EV",
    "XUV500"
  ],
  "Maruti Suzuki": [
    "Alto",
    "S-Presso",
    "Swift",
    "Baleno",
    "Dzire",
    "Vitara Brezza",
    "S-Cross",
    "Ertiga",
    "XL6",
    "Celerio",
    "Wagon R",
    "Frons",
    "Invicto",
    "Victoris",
    "Ignis",
    "Ciaz",
    "XL6",
    "Eeco",
    "Swift Sport",
    "Jimny"
  ],
  "Mercedes Benz": [
    "A-Class",
    "B-Class",
    "C-Class",
    "E-Class",
    "S-Class",
    "CLA",
    "GLA",
    "GLC",
    "GLE",
    "GLS",
    "G-Class",
    "EQC",
    "Maybach",
    "EQS",
    "GLB",
    "EQB",
    "AMG G63",
    "GLC Coupe",
    "AMG GT",
    "GLE Coupe"
  ],
  "MG Motor": [
    "ZS EV",
    "Astor",
    "Hector",
    "Gloster",
    "Cyberster",
    "M9",
    "Comet EV",
    "Gloster Blackstorm Edition",
    "MG 4 EV"
  ],
  "Nissan": [
    "Micra",
    "Sunny",
    "Magnite",
    "Kicks",
    "Terrano",
    "GT-R",
    "X-Trail",
    "Ariya",
    "Leaf"
  ],
  "Renault": [
    "Kwid",
    "Triber",
    "Kiger",
    "Duster",
    "Captur",
    "Lodgy",
    "Zoe",
    "Koleos"
  ],
  "Skoda": [
    "Rapid",
    "Octavia",
    "Superb",
    "Kushaq",
    "Slavia",
    "Fabia",
    "Kodiaq",
    "Enyaq",
    "Kamiq"
  ],
  "Tata Motors": [
    "Tiago",
    "Altroz",
    "Tigor",
    "Punch",
    "Nexon",
    "Harrier",
    "Safari",
    "Curvv",
    "Tigor EV",
    "Tiago EV",
    "Nexon EV",
    "Harrier EV",
    "Hexa"
  ],
  "Toyota": [
    "Glanza",
    "Urban Cruiser",
    "Innova Crysta",
    "Fortuner",
    "Camry",
    "Corolla Altis",
    "Land Cruiser",
    "Etios",
    "Yaris",
    "Hilux",
    "Innova Hycross",
    "Urban Cruiser Hyryder",
    "Rumion",
    "Vellfire",
    "Taisor",
    "Prius",
    "Corolla Cross",
    "Yaris Cross"
  ],
  "Volkswagen": [
    "Polo",
    "Vento",
    "Tiguan",
    "Taigun",
    "Virtus",
    "T-Cross",
    "Golf",
    "ID.4",
    "ID.3",
    "Arteon",
    "Touareg"
  ],
  "Volvo": [
    "XC40",
    "XC60",
    "XC90",
    "S60",
    "S90",
    "V60",
    "V90",
    "C40 Recharge",
    "V90 Cross Country"
  ]
};

List fuelList = ['E', '1/4', '1/2', '3/4', 'F'];

List<String> batteryBrands = [
  "Select Battery Name",
  "AC Delco India",
  "Amaron Batteries",
  "Exide Industries Ltd",
  "HBL Power Systems Ltd",
  "Livguard Batteries",
  "Luminous Power Technologies",
  "Okaya Power Group",
  "Rocket Batteries",
  "SF Sonic Batteries",
  "Tata Green Batteries",
];

List<String> filterBy = [
  "Today",
  "Yesterday",
  "Last Week",
  "This Month",
  "Last Month",
  "Date",
  "Date Range"
];

List<String> stockFilter = [
  "Filter By",
  "Today",
  "Yesterday",
  "Last Week",
  "This Month",
  "Last Month",
  "Date",
  "Date Range"
];

List<String> jobSheetFilterBy = [
  "All"
      "Today",
  "Yesterday",
  "Last Week",
  "This Month",
  "Last Month",
  "Date",
  "Date Range"
];
List<String> filterByDuedate = [
  "Today",
  "Yesterday",
  "Tomorrow",
  "Last Week",
  "This Month",
  "Last Month",
  "Date",
  "Date Range"
];

List<String> statusList = [
  "New Job",
  "In Progress",
  "Parts on Order",
  "Waiting for Approval",
  "On Hold",
  "Work Completed",
  "Ready for Delivery",
  "Delivered / Closed"
];

List<String> unitList = [
//"Select unit type",
  "UNT",
  "PCS",
  "LTR",
  "KGS",
  "MTR",
  "BOX"
];

List<String> stateList = [
//"Select unit type",
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Lakshadweep',
  'Puducherry',
];
List<String> gstList = [
  "None",
  "Exempted",
  "GST @0%",
  "GST @0.1%",
  "GST @0.25%",
  "GST @1.5%",
  "GST @3%",
  "GST @5%",
  "GST @6%",
  "GST @12%",
  "GST @13.8%",
  "GST @18%",
  "GST @14% + Cess @12%",
  "GST @28%",
  "GST @28% + Cess @12%",
  "GST @28% + Cess @60%",
];
List<String> igstList = [
  "None",
  "Exempted",
  "IGST @0%",
  "IGST @0.1%",
  "IGST @0.25%",
  "IGST @1.5%",
  "IGST @3%",
  "IGST @5%",
  "IGST @6%",
  "IGST @12%",
  "IGST @13.8%",
  "IGST @18%",
  "IGST @14% + Cess @12%",
  "IGST @28%",
  "IGST @28% + Cess @12%",
  "IGST @28% + Cess @60%",
];
List<String> vehicleModelList = ["Car", "Bike", "Truck", "Bus"];
List<String> paymentType = ["Cash", "Cheque", "Card", "UPI (Phonepe/Gpay)"];
List<String> paymentStatusList = ['Paid', 'Partially Paid', 'Unpaid'];
List<String> wheelAlignmentList = [
  'Checkup',
  'Proper Alignment',
];

List<String> wheelBalancingList = ['1', '2', '3', '4', '5'];
List<String> wheelAlloyList = ['1', '2', '3', '4', '5'];
List<String> wheelTyreList = ['1', '2', '3', '4', '5'];
List<String> wheelpunctureList = ['1', '2', '3', '4', '5'];
List<String> wheelRimOutList = ['1', '2', '3', '4', '5'];
List<String> wheelNewTyreList = ['1', '2', '3', '4', '5'];
